#!/usr/bin/env python

# --- AGGRESSIVE WARNING SUPPRESSION BLOCK ---
import os
import warnings
import logging
# 1. Environment variable for Transformers (often works best for startup warnings)
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "true"

# 2. Filter the specific UserWarning
warnings.filterwarnings(
    "ignore",
    message="The attention mask is not set and cannot be inferred from input because pad token is same as eos token.",
    category=UserWarning,
)

# 3. Suppress all FutureWarnings
warnings.filterwarnings("ignore", category=FutureWarning)

# 4. Silence general library logs (optional, but helpful)
logging.getLogger("transformers.modeling_utils").setLevel(logging.ERROR)
logging.getLogger("TTS").setLevel(logging.ERROR)
# ---------------------------------------------

import sys
import json
import argparse
from pathlib import Path
from datetime import datetime, timedelta



# --- START WARNING SUPPRESSION BLOCK ---
# 1. Suppress the torchaudio warning
warnings.filterwarnings(
    "ignore",
    message="In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec",
    category=UserWarning,
)
# 2. Suppress the Hugging Face/attention_mask warning
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "true"
warnings.filterwarnings(
    "ignore",
    message="The attention mask is not set and cannot be inferred from input because pad token is same as eos token.",
    category=UserWarning,
)
# 3. Suppress general future warnings often generated by PyTorch/Numpy
warnings.filterwarnings("ignore", category=FutureWarning)

# Optionally, silence excessive library logging (e.g., from TTS, transformers)
logging.getLogger("transformers.modeling_utils").setLevel(logging.ERROR)
logging.getLogger("TTS").setLevel(logging.ERROR)

# --- END WARNING SUPPRESSION BLOCK ---


import warnings

warnings.filterwarnings(
    "ignore",
    message="Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to",
    category=UserWarning,
)



# --- Internal Module Imports (The new structure) ---
# Assuming the refactored files are in the same package/directory
import config
import datamodel
import generator
import utils
import videopipeline

# ----------------------------------------------------

def setup_history(today: datetime.date, max_days: int) -> dict:
    """Loads existing history, cleans old entries, and returns the history dictionary."""
    history_path = config.used_history_file
    
    if history_path.exists():
        try:
            used_history = json.loads(history_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            print("⚠️ History file corrupted — resetting.")
            used_history = {}
    else:
        used_history = {}

    # Clean history: remove entries older than MAX_HISTORY_DAYS
    cutoff_date = today - timedelta(days=max_days)
    
    for rashi, entries in list(used_history.items()):
        if not isinstance(entries, list):
            used_history[rashi] = []
            continue
            
        used_history[rashi] = [
            e
            for e in entries
            if isinstance(e, dict)
            and "date" in e
            and datetime.strptime(e["date"], "%Y-%m-%d").date() >= cutoff_date
        ]
        
    return used_history

def main(test_mode=False):
  
    # --- START OVERALL TIMER ---
    import time # Import time inside main or globally if not done already
    overall_start_time = time.time()
    # ---------------------------

    today = datetime.now().date()

    
    # 1. Setup: Load Data, History, and Directories
    rashifal_data = datamodel.get_categorized_data()
    
    used_history = setup_history(today, max_days=10)
    daily_rashifal = {}
    
    # Create required directories
    config.output_dir.mkdir(parents=True, exist_ok=True)
    config.tmp_dir.mkdir(parents=True, exist_ok=True)
    config.tts_text_dir.mkdir(exist_ok=True)

    # 2. Text Generation and History Update
    for rashi in config.rashis:
        chosen_text = generator.generate_rashifal_text(rashi, rashifal_data)
        daily_rashifal[rashi] = chosen_text
        used_history.setdefault(rashi, []).append({"text": chosen_text, "date": str(today)})

    config.used_history_file.write_text(
        json.dumps(used_history, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"🧠 Updated {len(used_history)} rashis in history. Generating TTS now.")


    # Third-party heavy imports (keep here to control model loading)
    try:
        from TTS.api import TTS
        import torch
        from TTS.tts.configs.xtts_config import XttsConfig
        from TTS.tts.models.xtts import XttsAudioConfig, XttsArgs
        from TTS.config.shared_configs import BaseDatasetConfig
        # Safely adding globals for PyTorch unpickling
        try:
            torch.serialization.add_safe_globals(
                [XttsConfig, XttsAudioConfig, XttsArgs, BaseDatasetConfig]
            )
        except NameError:
            pass
    except ImportError:
        # If TTS or Torch is missing, print a clear error and exit
        print("🚨 Critical Error: The TTS and/or PyTorch libraries are not installed. Please check your virtual environment.")
        sys.exit(1)



    # 3. TTS Model Initialization
    # Decide device once
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"🧠 Using device: {device}")

    print(f"Loading TTS model: {config.tts_model}...")
    try:
        tts = TTS(config.tts_model)

        # Move model to GPU if available
        if device == "cuda":
            try:
                tts.to("cuda")
                print("✅ XTTS moved to GPU.")
            except Exception:
                print("⚠️ This XTTS version doesn't support .to(); staying on CPU.")
                device = "cpu"

    except Exception as e:
        print(f"🚨 Error loading TTS model: {e}")
        sys.exit(1)


    rashi_list = [config.rashis[0]] if test_mode else config.rashis
    generated_count = 0
    all_rashi_video_paths = []

    # 4. Main Generation Loop (TTS and Video Segment Creation)
    for rashi in rashi_list:
        text = daily_rashifal[rashi]
        
        # Check for Rashi video file presence
        video_number = config.RASHI_TO_VIDEO_MAP.get(rashi)
        rashi_video_input = config.RASHI_VIDEO_DIR / f"{video_number}{config.RASHI_VIDEO_EXTENSION}"
        
        if not video_number or not rashi_video_input.exists():
            print(
                f"🚨 ERROR: Input video for {rashi} (expected {video_number}{config.RASHI_VIDEO_EXTENSION}) not found. Skipping."
            )
            continue

        # Split text into chunks for TTS
        chunks = utils.split_text_safe(text, max_len=200)

        if test_mode and rashi == rashi_list[0]:
            chunks = [chunks[0]]
            print("⚡ Test mode: generating only the first chunk of the first rashi.")

        temp_files = []

        # --- 4a. Generate Chunks Audio & Text ---
        for i, chunk in enumerate(chunks):
            out_file = config.tmp_dir / f"{rashi}_{i}.wav"
            txt_file = config.tts_text_dir / f"{rashi}_{i}.txt"
            txt_file.write_text(chunk, encoding="utf-8")

            print(f"🎼 Generating TTS for {rashi}, chunk {i + 1}/{len(chunks)}...")

            try:
                tts.tts_to_file(
                    text=chunk,
                    speaker_wav=config.speaker_wav,
                    language="hi",
                    file_path=str(out_file),
                )
            except Exception as e:
                print(f"🛑 TTS failed for {rashi} chunk {i}: {e}. Skipping chunk.")
                continue

            if not out_file.exists() or out_file.stat().st_size == 0:
                print(f"Warning: TTS output missing or zero-length for {rashi}_{i}. Skipping chunk.")
                continue
                
            temp_files.append(str(out_file))
            
        # --- 4b. Merge chunks per rashi to get the final Rashi AUDIO file ---
        if not temp_files:
            continue
            
        rashi_concat_file = config.tmp_dir / f"{rashi}_concat.txt"
        with open(rashi_concat_file, "w", encoding="utf-8") as f:
            for wav in temp_files:
                # Use as_posix() for cross-platform FFmpeg compatibility
                f.write(f"file '{Path(wav).as_posix()}'\n")

        rashi_audio_path = config.tmp_dir / f"{rashi}.wav"
        rashi_text_path = config.tts_text_dir / f"{rashi}.txt"
        rashi_text_path.write_text("\n\n".join(chunks), encoding="utf-8")  # Save combined text

        # FFmpeg command to concatenate audio chunks (delegated to utils.run_ffmpeg_command)
        cmd = [
            "ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", str(rashi_concat_file),
            "-af", "volume=4.0,dynaudnorm=f=75", "-c:a", "pcm_s16le", str(rashi_audio_path),
        ]
        
        try:
            utils.run_ffmpeg_command(cmd, f"Rashi Chunk Merge: {rashi}")
        except Exception:
            print(f"❌ Failed to merge chunks for {rashi}. Skipping this rashi.")
            if test_mode:
                sys.exit(1)
            continue

        # --- 4c. GENERATE FINAL VIDEO SEGMENT FOR THIS RASHI ---
        video_segment_path = videopipeline.generate_video_segment(
            rashi_audio_path, rashi_text_path, config.output_dir, rashi
        )
        
        if video_segment_path and video_segment_path.exists():
            print(f"🎉 FINAL VIDEO SEGMENT GENERATED: {video_segment_path.name}\n")
            generated_count += 1
            all_rashi_video_paths.append(video_segment_path)  # <<< COLLECT PATH

        # Clean up temporary files for this Rashi
        rashi_concat_file.unlink(missing_ok=True)
        for f in temp_files:
            Path(f).unlink(missing_ok=True)
        rashi_audio_path.unlink(missing_ok=True)
        rashi_text_path.unlink(missing_ok=True)

        if test_mode:
            break

    # 5. Final Merge Step
    final_merge_successful = False

    if len(all_rashi_video_paths) > 1:
        print("\n🎬 Starting final merge of all Rashi videos...")
        final_merge_successful = videopipeline.final_video_merge(
            all_rashi_video_paths, config.tmp_dir, config.FINAL_VIDEO_BASE_DIR, config.date_str_format
        )
    elif len(all_rashi_video_paths) == 1:
        print("\n⚠️ Only one Rashi video was generated. Skipping merge.")
    else:
        print("\n❌ No Rashi videos were successfully generated. Nothing to merge.")
        
    # 6. Cleanup individual Rashi video segments after successful final merge
    if final_merge_successful:
        print("\n🧹 Cleaning up individual Rashi video segments...")
        for path in all_rashi_video_paths:
            try:
                path.unlink(missing_ok=True)
            except OSError as e:
                print(f"    ⚠️ Could not delete temporary video segment {path.name}: {e}")

    print(
        f"\n✨ Script finished. Generated {generated_count} individual Rashi videos in {config.FINAL_VIDEO_BASE_DIR.resolve()}."
    )

    # --- CALCULATE AND PRINT FINAL TIME ---
    overall_end_time = time.time()
    total_execution_time = overall_end_time - overall_start_time

    print(
        f"\n======================================================="
    )
    print(
        f"✨ Script finished. Generated {generated_count} individual Rashi videos in {config.FINAL_VIDEO_BASE_DIR.resolve()}."
    )
    print(
        f"⏱️ TOTAL EXECUTION TIME: {total_execution_time:.2f} seconds"
    )
    print(
        f"======================================================="
    )
    # ----------------------------------------

# ===== MAIN EXECUTION =====
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate daily rashifal video from TTS and subtitles."
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run in test mode (only processes the first chunk of the first rashi and breaks).",
    )
    args = parser.parse_args()
    main(test_mode=args.test)